---
dc_name: DC1

evpn_overlay_bgp_rtc: true

spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    # ASN to be used by BGP
    bgp_as: 65110
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: spine1-DC1
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 11
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.11/24
 
