underlay_routing_protocol: 
overlay_routing_protocol: 

underlay_isis_instance_name: CORE


p:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS
    # Pool of IPv4 addresses to configure interface Loopback0 used for Router ID
    loopback_ipv4_pool: 192.168.255.0/24
   
